### ISSUE TITLE
Any plans to add fitting capability to histogrammar?

### ISSUE THREAD

**Issue by IceMan81** [histogrammar/histogrammar-scala#22]
SImilar to https://root.cern.ch/root/html534/guides/users-guide/ROOTUsersGuide.html#fitting-histograms

**Comment by jpivarski** [comment]
No, an important point of Histogrammar is to do one job well— aggregating data— and offload plotting and statistical analysis, which includes fitting, to other libraries.

For example, you can use the export to PyROOT to do fitting.

Sorry that I didn't respond earlier: I just found out that I'm not automatically included in the "watch" list.
